/**:
  ros__parameters:
    x_p: 1.4
    x_i: 0.0
    x_d: 1.7
    y_p: 1.0
    y_i: 0.0
    y_d: 0.0
    z_p: 75.0
    z_i: 0.0
    z_d: 0.0
    yaw_rate_p: 7.0
    yaw_rate_i: 0.0
    yaw_rate_d: 0.0
    roll_p: 3.0 #subject to change
    roll_i: 0.0
    roll_d: 0.0
    roll_rate_p: 6.0 #subject to change
    roll_rate_i: 0.0
    roll_rate_d: 0.0