/**:
  ros__parameters:
    x_p: 0.75
    x_i: 0.0
    x_d: 0.1
    y_p: 0.75
    y_i: 0.0
    y_d: 0.0
    z_p: 300.0
    z_i: 1.0
    z_d: 0.0
    yaw_rate_p: 7.0
    yaw_rate_i: 0.0
    yaw_rate_d: 0.0
    roll_p: 3.0 #subject to change
    roll_i: 0.0
    roll_d: 0.0
    roll_rate_p: 6.0 #subject to change
    roll_rate_i: 0.0
    roll_rate_d: 0.0