/**:
  ros__parameters:
    x_p: 0.2
    x_i: 0.0
    x_d: 0.0
    y_p: 1.0
    y_i: 0.0
    y_d: 0.0
    z_p: 0.0
    z_i: 0.0
    z_d: 0.0
    yaw_p: 7.0
    yaw_i: 0.0
    roll_p: 3.0 #subject to change
    roll_i: 0.0
    roll_d: 0.0
    rollRate_p: 6.0 #subject to change
    rollRate_i: 0.0
    rollRate_d: 0.0